name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  fluttertoast: ^8.2.6
  cloud_firestore: ^5.2.0
  get: ^4.6.6
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_storage: ^12.2.0
  

  http: any
  uuid: ^4.4.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.0.11
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-bg.png"
  background_color: "#3A5F79"
  remove_alpha_ios: true




flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-bg.png
    - assets/images/paso-1-bg.png
    - assets/images/paso-2-bg.png
    - assets/images/paso-3-bg.png
    - assets/images/paso-4-bg.png
    - assets/images/importante-bg.png
  
  
